services:
  - type: web
    name: verifylink
    env: go
    buildCommand: |
      echo "Текущая директория: $(pwd)" &&
      echo "Содержимое проекта:" &&
      ls -la &&
      echo "Сборка приложения..." &&
      cd api &&
      go build -o ../app handler.go &&
      echo "Проверка билда:" &&
      ls -la ../app
    startCommand: ./app
    envVars:
      - key: PORT
        value: "10000"
      - key: GOOGLE_API_KEY
        value: AIzaSyBs96LPZ_Dk5Kmgj30oKh3jYsXlFa5DNA
