services:
  - type: web
    name: verifylink
    env: go
    buildCommand: |
      echo "Установка зависимостей..." &&
      go mod download &&
      echo "Копирование шаблонов..." &&
      mkdir -p templates &&
      cp -r ./templates/* ./api/templates/ &&
      echo "Сборка приложения..." &&
      cd api &&
      go build -o ../app &&
      echo "Настройка прав..." &&
      chmod -R 755 ../templates
    startCommand: ./app
    envVars:
      - key: PORT
        value: "10000"
      - key: GOOGLE_API_KEY
        value: AIzaSyBs96LPZ_DVk5Kmgj30oKh3jYsXlFa5DNA
